### ISSUE TITLE
会出书吗？不是知识星球系列文章的那种

### ISSUE THREAD

**Issue by guidongyuan** [2BAB/Extend-Android-Builds-zh#3]
不明白，知识星球如果一年到期了，是否还可以阅读书籍

**Comment by 2BAB** [comment]
你好，到期后可以继续阅读的，和您在其他地方购买在线电子书的体验一致。只是不再可以参与后续的更新和星球讨论。

<img width="778" alt="image" src="https://github.com/2BAB/Extend-Android-Builds-zh/assets/5710495/958426c4-47b7-4253-9005-13b79d5c7efc">

https://help.zsxq.com/howto/faq/user#xing-qiu-dao-qi-hou-hai-neng-bu-neng-cha-kan-zhi-qian-de-nei-rong
